Repository monkey-team-3801/on-board, pull requests merged in 2020-10, with the labels that each got.

#108 Responses
  .gitignore
  package.json
  src/client/AppProtectedRoutes.tsx
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/MultipleChoiceContainer.tsx
  src/client/responses/MultipleChoiceDisplay.tsx
  src/client/responses/ResponseOptionsContainer.tsx
  src/client/responses/ResponseTest.tsx
  src/client/responses/ShortAnswerDisplay.tsx
  src/client/responses/ShortAnswerDisplayContainer.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/types.ts
  src/events.ts
  src/server/database/schema/Response.ts
  src/server/database/schema/ResponseForm.ts
  src/server/routes/index.ts
  src/server/routes/response-handler.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement

#109 Participants list
  src/client/hooks/index.tsx
  src/client/hooks/useComponentDidUpdateEffect.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/breakoutAllocation.less
  src/client/rooms/classroom.less
  src/client/rooms/components/Participants.tsx
  src/client/rooms/components/UserDisplay.tsx
  src/client/rooms/components/UserDisplayAllocation.tsx
  src/client/rooms/components/index.tsx
  src/client/rooms/containers/ParticipantsContainer.tsx
  src/client/rooms/containers/RoomGroupingContainer.tsx
  src/client/rooms/containers/index.tsx
  src/client/video/index.tsx
  src/events.ts
  src/server/database/schema/Session.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/server/utils.ts
Labels: enhancement

#111 Loading state and general restructure
  src/client/App.tsx
  src/client/AppProtectedRoutes.tsx
  src/client/announcements/Announcements.less
  src/client/announcements/AnnouncementsContainer.tsx
  src/client/announcements/CreateAnnouncementsForm.tsx
  src/client/auth/SecuredRoute.tsx
  src/client/classes/ClassesPageContainer.tsx
  src/client/classes/ClassroomDisplayContainer.tsx
  src/client/classes/PrivateRoomDisplayContainer.tsx
  src/client/components/ButtonWithLoadingProp.tsx
  src/client/components/ContainerWrapper.tsx
  src/client/components/Loader.tsx
  src/client/components/LoaderButton.tsx
  src/client/components/SimpleDatepicker.tsx
  src/client/components/index.tsx
  src/client/components/loader.less
  src/client/courses/EnrolFormContainer.tsx
  src/client/filehandler/FileContainer.less
  src/client/filehandler/FileContainer.tsx
  src/client/filehandler/UploadContainer.less
  src/client/filehandler/UploadContainer.tsx
  src/client/home/Classes.less
  src/client/home/ClassesContainer.tsx
  src/client/home/Homepage.less
  src/client/home/UpcomingClass.tsx
  src/client/home/UpcomingClassesContainer.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/logo_white.png
  src/client/navbar/Navbar.less
  src/client/rooms/CreateRoomForm.tsx
  src/client/rooms/RoomDisplayContainer.tsx
  src/client/rooms/ScheduleRoomFormContainer.tsx
  src/client/rooms/components/BreakoutRoomModal.tsx
  src/client/rooms/index.tsx
  src/client/styles/App.less
  src/client/timetable/calendar/Calendar.tsx
  src/client/types.ts
  src/client/user/Login.less
  src/client/user/LoginContainer.tsx
  src/client/user/LoginPage.tsx
  src/client/user/RegisterContainer.tsx
  src/client/utils.ts
  src/server/database/schema/Session.ts
  src/server/jobs/job-runner.ts
  src/server/routes/filehandler.ts
  src/server/routes/job.ts
  src/server/routes/session.ts
  src/server/utils.ts
  src/types.ts
Labels: enhancement

#113 Apply general layout
  src/client/chat/Chat.less
  src/client/chat/ChatContainer.tsx
  src/client/components/ButtonWithLoadingProp.tsx
  src/client/components/Loader.tsx
  src/client/components/loader.less
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/FormListContainer.tsx
  src/client/responses/MultipleChoiceContainer.tsx
  src/client/responses/MultipleChoiceDisplay.tsx
  src/client/responses/ResponseOptionsContainer.tsx
  src/client/responses/ResponseTest.tsx
  src/client/responses/ResponsesModal.tsx
  src/client/responses/index.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/rooms/classroom.less
  src/client/rooms/components/BreakoutRoomModal.tsx
  src/client/rooms/components/Participants.tsx
  src/client/rooms/containers/SessionContainer.tsx
  src/client/rooms/containers/SidePanelContainer.tsx
  src/client/rooms/containers/index.tsx
  src/client/rooms/room.less
  src/client/styles/App.less
  src/server/routes/chat.ts
  src/server/routes/response-handler.ts
  src/types.ts
Labels: enhancement

#112 File system update
  src/client/AppProtectedRoutes.tsx
  src/client/filehandler/FileContainer.less
  src/client/filehandler/FileContainer.tsx
  src/client/filehandler/FileModal.tsx
  src/client/filehandler/UploadContainer.less
  src/client/filehandler/UploadContainer.tsx
  src/client/filehandler/UploadTest.tsx
  src/client/navbar/Navbar.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/events.ts
  src/server/database/schema/File.ts
  src/server/database/schema/Session.ts
  src/server/routes/filehandler.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/server/utils.ts
Labels: enhancement

#116 Fix chat events not working and chats failing on breakout rooms
  src/client/AppProtectedRoutes.tsx
  src/client/chat/Chat.less
  src/client/chat/ChatContainer.tsx
  src/client/chat/Log.tsx
  src/client/hooks/useTransformingSocket.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/rooms/containers/SessionContainer.tsx
  src/client/rooms/containers/SidePanelContainer.tsx
  src/server/database/schema/Session.ts
  src/server/routes/chat.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/types.ts
Labels: bug

#117 Responses improvements
  package.json
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/MultipleChoiceContainer.tsx
  src/client/responses/MultipleChoiceDisplay.tsx
  src/client/responses/MultipleChoiceResultsChart.tsx
  src/client/responses/ResponseOptionsContainer.tsx
  src/client/responses/ShortAnswerDisplay.tsx
  src/client/responses/ShortAnswerDisplayContainer.tsx
  src/client/responses/ShortAnswerResultsTable.tsx
Labels: bug, enhancement

#120 Improved rooms
  src/client/announcements/CreateAnnouncementsForm.tsx
  src/client/classes/ClassroomDisplayContainer.tsx
  src/client/classes/EditClassroomModal.tsx
  src/client/components/SimpleDatepicker.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/rooms/CreateClassroomContainer.tsx
  src/client/rooms/ScheduleRoomFormContainer.tsx
  src/client/rooms/components/ScheduleRoomForm.tsx
  src/client/rooms/components/index.tsx
  src/client/rooms/index.tsx
  src/client/utils.ts
  src/server/database/schema/Job.ts
  src/server/database/schema/Session.ts
  src/server/jobs/ScheduleHandler.ts
  src/server/jobs/job-runner.ts
  src/server/routes/job.ts
  src/server/routes/session.ts
  src/server/utils.ts
  src/types.ts
Labels: enhancement

#121 File responses
  public/notification.wav
  src/client/filehandler/FileContainer.tsx
  src/client/filehandler/FileModal.tsx
  src/client/filehandler/UploadContainer.tsx
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/FileDisplay.tsx
  src/client/responses/FileResponseOptionsContainer.tsx
  src/client/responses/ResponseOptionsContainer.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/server/database/schema/File.ts
  src/server/database/schema/ResponseForm.ts
  src/server/database/schema/Session.ts
  src/server/routes/filehandler.ts
  src/server/routes/response-handler.ts
  src/server/routes/session.ts
  src/server/routes/user.ts
  src/types.ts
Labels: enhancement

#122 Fixed notification playing when it shouldnt
  src/client/rooms/ClassroomPageContainer.tsx
  src/server/routes/session.ts
Labels: bug

#126 Updated readme
  README.md
Labels: documentation

#132 Apply completely new theme to on-board
  package.json
  src/client/App.tsx
  src/client/AppProtectedRoutes.tsx
  src/client/Indicators/ClassOpenIndicator.tsx
  src/client/Indicators/Indicator.less
  src/client/announcements/AnnouncementEntry.tsx
  src/client/announcements/Announcements.less
  src/client/announcements/AnnouncementsContainer.tsx
  src/client/classes/ClassContainer.tsx
  src/client/classes/Classes.less
  src/client/classes/ClassroomDisplayContainer.tsx
  src/client/components/ContainerWrapper.tsx
  src/client/filehandler/FileContainer.less
  src/client/filehandler/FileContainer.tsx
  src/client/filehandler/FileModal.tsx
  src/client/filehandler/UploadContainer.less
  src/client/filehandler/UploadContainer.tsx
  src/client/home/Homepage.less
  src/client/home/UpcomingClassesContainer.tsx
  src/client/navbar/Navbar.less
  src/client/navbar/Navbar.tsx
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/FormListContainer.tsx
  src/client/responses/MultipleChoiceDisplay.tsx
  src/client/responses/MultipleChoiceResultsChart.tsx
  src/client/responses/ResponsesModal.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/ScheduleRoomFormContainer.tsx
  src/client/rooms/components/ScheduleRoomForm.tsx
  src/client/rooms/components/UserDisplayAllocation.tsx
  src/client/rooms/containers/RoomGroupingContainer.tsx
  src/client/styles/App.less
  src/client/styles/Colours.less
  src/client/timetable/calendar/Calendar.less
  src/client/timetable/calendar/UpcomingEventsContainer.tsx
  src/client/user/Login.less
  src/client/user/LoginContainer.tsx
Labels: enhancement, high priority, ui/ux

#133 Fix endpoints
  src/server/routes/filehandler.ts
  src/server/routes/session.ts
  src/server/server.ts
Labels: bug

#134 Ben's list
  src/client/classes/ClassContainer.tsx
  src/client/classes/PrivateRoomDisplayContainer.tsx
  src/client/filehandler/UploadContainer.tsx
  src/client/responses/DisplayContainer.tsx
  src/client/responses/DisplayResultsContainer.tsx
  src/client/responses/MultipleChoiceResultsChart.tsx
  src/client/rooms/CreatePrivateRoomContainer.tsx
  src/client/rooms/components/BreakoutRoomModal.tsx
  src/client/rooms/containers/BreakoutRoomAllocationContainer.tsx
  src/client/rooms/containers/ParticipantsContainer.tsx
  src/server/routes/session.ts
Labels: bug

#136 Scripts for fetching courses implemented
  package.json
  scripts/fetchCourse.js
  src/types.ts
Labels: enhancement

#138 Add private messaging
  src/client/AppProtectedRoutes.tsx
  src/client/AppRouter.tsx
  src/client/chat/Chat.less
  src/client/chat/ChatLog.tsx
  src/client/chat/ChatModal.tsx
  src/client/chat/ChatSession.tsx
  src/client/chat/components/UserList.tsx
  src/client/chat/components/index.tsx
  src/client/chat/index.tsx
  src/client/context/ChatModalStatusContext.tsx
  src/client/context/index.tsx
  src/client/navbar/Navbar.less
  src/client/navbar/Navbar.tsx
  src/client/types.ts
  src/events.ts
  src/server/database/schema/UserToUserChat.ts
  src/server/database/schema/index.ts
  src/server/routes/chat.ts
  src/server/routes/user.ts
  src/server/server.ts
Labels: enhancement, high priority

#141 Chat improvements
  src/client/AppProtectedRoutes.tsx
  src/client/chat/Chat.less
  src/client/chat/ChatModal.tsx
  src/client/chat/ChatSession.tsx
  src/client/chat/components/UserList.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/types.ts
Labels: enhancement, ui/ux

#143 Generic profile component
  src/client/AppProtectedRoutes.tsx
  src/client/AppRouter.tsx
  src/client/announcements/AnnouncementEntry.tsx
  src/client/chat/ChatModal.tsx
  src/client/chat/components/UserList.tsx
  src/client/components/ProfilePicture.tsx
  src/client/components/index.tsx
  src/client/context/ChatModalStatusContext.tsx
  src/client/rooms/components/UserDisplay.tsx
  src/client/styles/App.less
  src/client/user/ProfilePictureContainer.less
  src/client/user/ProfilePictureContainer.tsx
Labels: enhancement

#142 User page
  .gitignore
  .vscode/settings.json
  src/client/AppProtectedRoutes.tsx
  src/client/courses/EnrolFormContainer.tsx
  src/client/filehandler/UploadContainer.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/navbar/Navbar.tsx
  src/client/types.ts
  src/client/user/profile/AvatarSettings.tsx
  src/client/user/profile/GeneralOptionsContainer.tsx
  src/client/user/profile/ProfileSettingsContainer.tsx
  src/client/user/profile/Settings.less
  src/server/routes/user.ts
Labels: enhancement

#145 Additional info container
  src/client/AppProtectedRoutes.tsx
  src/client/announcements/AnnouncementEntry.tsx
  src/client/announcements/AnnouncementsContainer.tsx
  src/client/chat/ChatModal.tsx
  src/client/components/ProfilePicture.tsx
  src/client/home/Homepage.less
  src/client/home/UserHomeContainer.tsx
  src/client/home/containers/CourseDetailsContainer.tsx
  src/client/home/containers/CourseStaffList.tsx
  src/client/home/containers/UserInfoContainer.tsx
  src/client/home/containers/index.tsx
  src/client/rooms/components/UserDisplay.tsx
  src/client/utils.ts
  src/server/routes/course.ts
Labels: enhancement

#146 Fixed delete route not searching for classrooms
  src/server/routes/filehandler.ts
Labels: bug

#147 User views
  public/announcement.png
  public/classroom.jpg
  public/privateroom.png
  src/client/components/ContainerWrapper.tsx
  src/client/home/Homepage.less
  src/client/home/UserHomeContainer.tsx
  src/client/home/containers/CreateContainer.tsx
  src/client/home/containers/CreateContainerModal.tsx
  src/client/home/containers/UserInfoContainer.tsx
  src/client/home/types.ts
  src/client/rooms/components/ScheduleRoomForm.tsx
  src/client/user/profile/Settings.less
  src/client/utils.ts
Labels: enhancement, ui/ux

#149 Added breakout rooms lists
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/components/BreakoutRoomListModal.tsx
  src/client/rooms/components/index.tsx
  src/client/rooms/containers/RoomGroupingContainer.tsx
Labels: enhancement

#150 Add streaming for participants with webcams
  src/client/hooks/useMyPeer.tsx
  src/client/peer/peer.ts
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/rooms/classroom.less
  src/client/rooms/components/Participants.tsx
  src/client/rooms/components/SelfStreamDisplay.tsx
  src/client/rooms/components/UserStreamDisplay.tsx
  src/client/rooms/containers/ParticipantsContainer.tsx
  src/client/rooms/containers/SidePanelContainer.tsx
  src/client/videostreaming/MyVideo.tsx
  src/client/videostreaming/RemotePeerVideo.tsx
  src/client/videostreaming/StreamVideo.tsx
Labels: enhancement

#151 Added header to homepage
  package.json
  src/@types/react-fade-in/index.d.ts
  src/client/AppProtectedRoutes.tsx
  src/client/classes/ClassroomDisplayContainer.tsx
  src/client/classes/PrivateRoomDisplayContainer.tsx
  src/client/home/Homepage.less
  src/client/home/UpcomingClassesContainer.tsx
  src/client/home/UserHeaderJumbotron.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/navbar/Navbar.less
  src/client/navbar/Navbar.tsx
  src/client/styles/App.less
  tsconfig.json
Labels: enhancement, ui/ux

#156 Fix updating enrolment not updating calendar
  src/client/courses/EnrolFormContainer.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/timetable/calendar/Calendar.tsx
  src/client/user/profile/ProfileSettingsContainer.tsx
Labels: bug

#155 Calendar styling
  src/client/timetable/calendar/Calendar.less
  src/client/timetable/calendar/Calendar.tsx
  src/client/timetable/calendar/CalendarDay.less
  src/client/timetable/calendar/CalendarDay.tsx
  src/client/timetable/calendar/CalendarHeading.tsx
  src/client/timetable/calendar/Event.tsx
  src/client/timetable/calendar/UpcomingEventsContainer.tsx
Labels: enhancement, ui/ux

#157 Improved private room
  src/client/canvas/Canvas.less
  src/client/canvas/DrawingCanvas.tsx
  src/client/rooms/PrivateRoom.less
  src/client/rooms/PrivateRoomContainer.tsx
Labels: enhancement, ui/ux

#163 Use screen record hook
  package.json
  src/client/hooks/useScreenRecording.tsx
Labels: enhancement

#160 Classroom page
  debug.log
  src/client/canvas/DrawingCanvas.tsx
  src/client/chat/Chat.less
  src/client/chat/ChatContainer.tsx
  src/client/chat/ChatLog.tsx
  src/client/chat/ChatSession.tsx
  src/client/filehandler/FileModal.tsx
  src/client/hooks/useScreenSharing.tsx
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoom.less
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/rooms/classroom.less
  src/client/rooms/components/BreakoutRoomListModal.tsx
  src/client/rooms/components/HostDisplay.tsx
  src/client/rooms/components/Participants.tsx
  src/client/rooms/components/Progress.tsx
  src/client/rooms/components/StreamControl.tsx
  src/client/rooms/components/index.tsx
  src/client/rooms/containers/ParticipantsContainer.tsx
  src/client/rooms/containers/SessionContainer.tsx
  src/client/rooms/containers/SidePanelContainer.less
  src/client/rooms/containers/SidePanelContainer.tsx
  src/client/rooms/room.less
  src/client/styles/App.less
  src/client/videostreaming/RemotePeerVideo.tsx
  src/client/videostreaming/ScreenSharingContainer.tsx
  src/client/videostreaming/StreamVideo.less
  src/client/videostreaming/StreamVideo.tsx
  src/client/videostreaming/VideoContainer.less
  src/server/routes/session.ts
Labels: enhancement, high priority, ui/ux

#164 Added simple auth to most routes
  src/server/routes/filehandler.ts
  src/server/routes/index.ts
  src/server/routes/user.ts
  src/server/server.ts
Labels: enhancement
