Repository monkey-team-3801/on-board, pull requests merged in 2020-09, with the labels that each got.

#72 Fixed bug where chat input remained when message sent
  src/client/chat/ChatContainer.tsx
Labels: bug

#73 Announcements / Course Enrollment
  package-lock.json
  package.json
  src/client/AppProtectedRoutes.tsx
  src/client/AppRouter.tsx
  src/client/announcements/AnnouncementsContainer.tsx
  src/client/announcements/CreateAnnouncementsForm.tsx
  src/client/announcements/index.tsx
  src/client/auth/SecuredRoute.tsx
  src/client/chat/ChatContainer.tsx
  src/client/courses/EnrolFormContainer.tsx
  src/client/courses/index.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/hooks/useFetch.tsx
  src/client/hooks/useSocket.tsx
  src/client/hooks/useTransformingSocket.tsx
  src/client/index.tsx
  src/client/io/socket.ts
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/types.ts
  src/client/user/LoginContainer.tsx
  src/client/user/LoginPage.tsx
  src/client/user/RegisterContainer.tsx
  src/events.ts
  src/server/database/schema/Course.ts
  src/server/database/schema/Job.ts
  src/server/database/schema/User.ts
  src/server/jobs/ScheduleHandler.ts
  src/server/jobs/job-runner.ts
  src/server/routes/course.ts
  src/server/routes/index.ts
  src/server/routes/job.ts
  src/server/routes/user.ts
  src/server/server.ts
  src/server/types.ts
  src/server/utils.ts
  src/types.ts
Labels: enhancement

#83 Added simple error handling
  src/client/hooks/useDynamicFetch.tsx
  src/client/types.ts
  src/client/user/LoginPage.tsx
  src/client/utils.ts
  src/server/routes/course.ts
  src/server/routes/session.ts
  src/server/routes/user.ts
  src/server/server.ts
Labels: enhancement

#81 Login registration
  package-lock.json
  package.json
  src/client/hooks/useDynamicFetch.tsx
  src/client/logo_white.svg
  src/client/particles/ParticlesContainer.tsx
  src/client/particles/index.tsx
  src/client/styles/App.less
  src/client/styles/Login.less
  src/client/styles/index.less
  src/client/styles/logo_white.png
  src/client/types.ts
  src/client/user/LoginContainer.tsx
  src/client/user/LoginPage.tsx
  src/client/user/RegisterContainer.tsx
Labels: enhancement, ui/ux

#80 Fix deleting classroom sessions
  src/client/home/UserHomeContainer.tsx
  src/server/routes/session.ts
  src/types.ts
Labels: bug, high priority

#84 Use better login/registration request status codes
  src/server/routes/user.ts
Labels: bug

#90 Avatar system
  package-lock.json
  package.json
  src/client/AppProtectedRoutes.tsx
  src/client/filehandler/FileContainer.tsx
  src/client/filehandler/UploadContainer.tsx
  src/client/filehandler/UploadTest.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/styles/FileContainer.less
  src/client/styles/UploadContainer.less
  src/client/user/LoginContainer.tsx
  src/client/user/ProfilePictureContainer.less
  src/client/user/ProfilePictureContainer.tsx
  src/client/user/RegisterContainer.tsx
  src/events.ts
  src/server/database/schema/Session.ts
  src/server/database/schema/User.ts
  src/server/routes/filehandler.ts
  src/server/routes/index.ts
  src/server/routes/user.ts
  src/server/server.ts
  src/setupProxy.js
  src/types.ts
Labels: enhancement

#92 Drawing canvas
  package-lock.json
  package.json
  src/client/canvas/DrawingCanvas.tsx
  src/client/canvas/index.tsx
  src/client/chat/ChatContainer.tsx
  src/client/colour/ColourPicker.tsx
  src/client/colour/index.tsx
  src/client/hooks/useSocket.tsx
  src/client/hooks/useTransformingSocket.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/events.ts
  src/server/database/schema/Session.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement

#93 Index styling
  .vscode/settings.json
  package.json
  src/client/App.tsx
  src/client/AppProtectedRoutes.tsx
  src/client/announcements/AnnouncementEntry.tsx
  src/client/announcements/Announcements.less
  src/client/announcements/AnnouncementsContainer.tsx
  src/client/announcements/CreateAnnouncementsForm.tsx
  src/client/classes/ClassesPageContainer.tsx
  src/client/classes/index.tsx
  src/client/components/ClassOpenIndicator.less
  src/client/components/ContainerWrapper.tsx
  src/client/components/index.tsx
  src/client/home/Classes.less
  src/client/home/ClassesContainer.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/navbar/Navbar.less
  src/client/navbar/Navbar.tsx
  src/client/navbar/NavbarData.tsx
  src/client/navbar/index.tsx
  src/client/rooms/CreateRoomForm.tsx
  src/client/rooms/CreateRoomPage.tsx
  src/client/rooms/ScheduleRoomFormContainer.tsx
  src/client/rooms/index.tsx
  src/client/styles/App.less
  src/client/styles/Colours.less
  src/client/styles/Homepage.less
  src/client/styles/Login.less
  src/client/styles/index.less
  src/client/timetable/Calendar.less
  src/client/timetable/Calendar.tsx
  src/client/timetable/CalendarHeading.tsx
  src/client/timetable/UpcomingEventsContainer.tsx
  src/client/timetable/index.tsx
  src/server/database/schema/Course.ts
  src/server/jobs/job-runner.ts
  src/server/routes/session.ts
  src/types.ts
Labels: enhancement, ui/ux

#94 Fix login screen not displaying error messages
  src/client/user/LoginContainer.tsx
  src/client/utils.ts
Labels: bug

#95 Better canvas
  package-lock.json
  package.json
  src/client/canvas/Canvas.less
  src/client/canvas/DrawingCanvas.tsx
  src/client/colour/ColourPicker.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/utils.ts
  src/events.ts
  src/server/database/index.ts
  src/server/database/schema/Session.ts
  src/server/database/schema/SessionCanvas.ts
  src/server/database/schema/index.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement
