Repository monkey-team-3801/on-board, pull requests merged in 2020-08, with the labels that each got.

#5 GitHub actions check
  .github/workflows/node.js.yml
  README.md
  config/webpack.config.js
  package.json
  src/App.test.tsx
  src/App.tsx
  tests/App.test.tsx
Labels: enhancement

#6 Setup heroku deployment
  .github/workflows/deploy-heroku.yaml
  procfile
Labels: enhancement

#9 Create CODEOWNERS
  .github/workflows/CODEOWNERS
Labels: enhancement

#16 Setup health checking in github actions
  .github/workflows/deploy-heroku.yaml
  src/server/routes/health-check.ts
  src/server/server.ts
Labels: enhancement

#48 Added placeholder routes
  package-lock.json
  package.json
  src/client/App.tsx
  src/client/AppRouter.tsx
  src/client/containers/ClassroomPageContainer.tsx
  src/client/containers/HomePageContainer.tsx
  src/client/containers/PrivateRoomContainer.tsx
Labels: enhancement

#50 Setup MongoDB
  .gitignore
  package-lock.json
  package.json
  src/server/database/database.ts
  src/server/database/index.ts
  src/server/server.ts
Labels: enhancement, high priority

#49 Add generic fetch hook
  package-lock.json
  package.json
  src/client/hooks/index.tsx
  src/client/hooks/useFetch.tsx
  src/client/types.ts
  src/client/utils.ts
Labels: enhancement

#46 Type safe route handlers
  .eslintrc
  .prettierignore
  src/server/routes/health-check.ts
  src/server/server.ts
  src/server/types.ts
  src/server/utils.ts
Labels: enhancement

#55 Setup SocketIO and global sessions
  config/webpackServer.config.js
  package-lock.json
  package.json
  src/client/AppRouter.tsx
  src/client/chat/ChatContainer.tsx
  src/client/chat/index.tsx
  src/client/containers/HomePageContainer.tsx
  src/client/containers/PrivateRoomContainer.tsx
  src/client/hooks/index.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/hooks/useFetch.tsx
  src/client/hooks/useSocket.tsx
  src/client/hooks/useTransformingSocket.tsx
  src/client/styles/App.less
  src/events.ts
  src/server/database/index.ts
  src/server/database/schema/Session.ts
  src/server/database/schema/index.ts
  src/server/routes/chat.ts
  src/server/routes/index.ts
  src/server/routes/session.ts
  src/server/server.ts
  src/server/utils.ts
  src/types.ts
Labels: enhancement, high priority

#56 Move socketIO event before database update
  src/server/routes/chat.ts
Labels: bug

#61 Timetable
  .gitignore
  package-lock.json
  package.json
  src/client/AppRouter.tsx
  src/client/timetable/Calendar.less
  src/client/timetable/Calendar.tsx
  src/client/timetable/CalendarDay.less
  src/client/timetable/CalendarDay.tsx
  src/client/timetable/CalendarHeading.tsx
  src/server/database/index.ts
  src/server/database/schema/Course.ts
  src/server/database/schema/index.ts
  src/server/routes/course.ts
  src/server/routes/index.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement, high priority

#62 Auth login persistence
  package-lock.json
  package.json
  src/client/AppRouter.tsx
  src/client/auth/SecuredRoute.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/hooks/useDynamicFetch.tsx
  src/client/hooks/utils.ts
  src/client/rooms/ClassroomPageContainer.tsx
  src/client/rooms/CreateRoomPage.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/types.ts
  src/client/user/LoginContainer.tsx
  src/client/user/LoginPage.tsx
  src/client/user/RegisterContainer.tsx
  src/server/database/schema/User.ts
  src/server/database/schema/index.ts
  src/server/routes/auth.ts
  src/server/routes/index.ts
  src/server/routes/user.ts
  src/server/routes/utils.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement, high priority

#64 Use react-bootstrap
  package-lock.json
  package.json
  src/client/App.tsx
  src/client/AppRouter.tsx
  src/client/chat/ChatContainer.tsx
  src/client/chat/ChatLog.tsx
  src/client/home/UserHomeContainer.tsx
  src/client/rooms/CreateRoomPage.tsx
  src/client/rooms/PrivateRoomContainer.tsx
  src/client/rooms/RoomDisplayContainer.tsx
  src/client/styles/App.less
  src/client/user/LoginContainer.tsx
  src/client/user/LoginPage.tsx
  src/client/user/RegisterContainer.tsx
Labels: enhancement, ui/ux

#66 Improve chat style and functionality
  src/client/chat/ChatContainer.tsx
  src/client/chat/ChatLog.tsx
  src/client/chat/Log.tsx
  src/client/hooks/useSocket.tsx
  src/client/hooks/useTransformingSocket.tsx
  src/client/io/index.ts
  src/client/io/socket.ts
  src/client/styles/App.less
  src/events.ts
  src/server/routes/chat.ts
  src/server/server.ts
  src/types.ts
Labels: enhancement, ui/ux

#67 Event/Job system
  package-lock.json
  package.json
  src/server/database/schema/Job.ts
  src/server/database/schema/index.ts
  src/server/jobs/ScheduleHandler.ts
  src/server/jobs/index.ts
  src/server/routes/utils.ts
  src/server/server.ts
  src/server/types.ts
  src/server/utils.ts
Labels: enhancement, high priority
